// Code generated by go-bindata.
// sources:
// bindata.go
// editorconfig/.editorconfig
// glide/glide.yaml
// makefile/Makefile
// DO NOT EDIT!

package data

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindataGo = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func bindataGoBytes() ([]byte, error) {
	return bindataRead(
		_bindataGo,
		"bindata.go",
	)
}

func bindataGo() (*asset, error) {
	bytes, err := bindataGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata.go", size: 0, mode: os.FileMode(420), modTime: time.Unix(1479621960, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _editorconfigEditorconfig = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x2a\xca\xcf\x2f\x51\xb0\x55\x28\x29\x2a\x4d\xe5\xe2\x8a\xd6\x8a\xe5\x4a\xcd\x4b\x89\xcf\x4f\x8b\xcf\xc9\xcc\x4b\x05\x8a\xe7\xa4\x71\x65\xe6\x15\xa7\x16\x95\xc4\xa7\x65\xe6\x25\xe6\xc4\xe7\xa5\x96\x43\x65\xc0\x3a\x32\xf3\x52\x52\xf3\x4a\xe2\x8b\x4b\x2a\x73\x40\x62\xc5\x05\x89\xc9\x08\xc1\xcc\x2a\x90\x98\x09\xd0\x58\xdf\xc4\xec\xd4\xb4\xcc\x9c\xd4\x58\x74\x0d\x25\x89\x49\x18\xca\x01\x01\x00\x00\xff\xff\xc8\xd9\x9e\x08\x92\x00\x00\x00")

func editorconfigEditorconfigBytes() ([]byte, error) {
	return bindataRead(
		_editorconfigEditorconfig,
		"editorconfig/.editorconfig",
	)
}

func editorconfigEditorconfig() (*asset, error) {
	bytes, err := editorconfigEditorconfigBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "editorconfig/.editorconfig", size: 146, mode: os.FileMode(420), modTime: time.Unix(1479504906, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _glideGlideYaml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x2a\x48\x4c\xce\x4e\x4c\x4f\xb5\x52\xa8\xae\xd6\x0b\x80\xb0\xfd\x12\x73\x53\x6b\x6b\xb9\x32\x73\x0b\xf2\x8b\x4a\xac\x14\xa2\x63\xb9\x00\x01\x00\x00\xff\xff\x5d\x8a\xe0\xe3\x25\x00\x00\x00")

func glideGlideYamlBytes() ([]byte, error) {
	return bindataRead(
		_glideGlideYaml,
		"glide/glide.yaml",
	)
}

func glideGlideYaml() (*asset, error) {
	bytes, err := glideGlideYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "glide/glide.yaml", size: 37, mode: os.FileMode(420), modTime: time.Unix(1479515893, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _makefileMakefile = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x4c\x8d\xd1\xca\x82\x40\x10\x46\xaf\x9d\xa7\x18\xf8\x7f\xd8\x14\x5a\xef\x07\x84\x5e\xa0\xe8\xde\x54\x36\x9d\xd4\x5a\x73\xd9\x5d\xea\xc2\x7c\xf7\xd6\x28\xf0\x6e\xce\xe1\x30\xdf\xa0\x6e\x7c\xe9\x35\x57\x4d\x6f\x23\xca\xf0\x7f\xa3\xce\xce\x28\xdf\x85\xcb\x75\xac\x35\x9a\x67\x13\xc7\x00\xca\x98\xea\xae\x06\x8e\x96\x6a\x9a\xe4\xd1\x8e\x57\xae\xfd\x21\xa8\x79\x06\xd0\xbd\xf3\x04\xd1\xae\xb5\x6c\x50\x94\x79\xf9\x97\x53\xf8\x53\x33\x15\x85\x4c\x48\xe0\xfe\x3b\x84\x2f\xfc\x34\xdb\x07\x0a\xca\xc4\x1a\xcb\x93\x5c\xd8\x71\x83\xc2\xa5\x24\x93\x34\x6d\xd7\xe2\x87\xa3\xf5\xf0\x0e\x00\x00\xff\xff\xaa\x44\xaf\x76\xb8\x00\x00\x00")

func makefileMakefileBytes() ([]byte, error) {
	return bindataRead(
		_makefileMakefile,
		"makefile/Makefile",
	)
}

func makefileMakefile() (*asset, error) {
	bytes, err := makefileMakefileBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "makefile/Makefile", size: 184, mode: os.FileMode(420), modTime: time.Unix(1479504751, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"bindata.go": bindataGo,
	"editorconfig/.editorconfig": editorconfigEditorconfig,
	"glide/glide.yaml": glideGlideYaml,
	"makefile/Makefile": makefileMakefile,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"bindata.go": &bintree{bindataGo, map[string]*bintree{}},
	"editorconfig": &bintree{nil, map[string]*bintree{
		".editorconfig": &bintree{editorconfigEditorconfig, map[string]*bintree{}},
	}},
	"glide": &bintree{nil, map[string]*bintree{
		"glide.yaml": &bintree{glideGlideYaml, map[string]*bintree{}},
	}},
	"makefile": &bintree{nil, map[string]*bintree{
		"Makefile": &bintree{makefileMakefile, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

